cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

cloudcart/urls.py
from django.contrib import admin
from django.urls import path , include
from shop import views
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/' , include('shop.urls')),
    path('search_app', include('search_app.urls')),
    path('cart', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documet_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('' , views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'
    
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return self.product
    

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    
    def __str__(self):
        return '{}'.format(self.name)
    
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10 , decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug , self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.views import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
            )
        cart.save()
    
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
            )
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_details(request, total=0 , counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity   
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items = cart_items, total= total, counter = counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    
    return redirect('cart:cart_detail')
    print("control is here -----------")

search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.

def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query':query, 'products':products})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Product,Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def index(request):
    text_var = 'This is my Django app webpage'
    return HttpResponse(text_var)

#category View
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    # Paginoator code ##
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page' , '1'))
    except :
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    
    return render(request,'shop/category.html', {'category':c_page, 'products':products}) 



def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
   Shopping Cart
{%  endblock %}
{% block title %}
   Cart 
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Cart is empty
                </h1>
                <p class="text-center">
                    Please click <a href="{% url 'shop:allProdCat' %}">Here</a> to continue Shopping
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title"> 
                    Your Cart
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your Items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="c_item.product.get_absolute_url"><img class="float-left rounded custom_image" src="{{ c_item.product.image.url}}" alt=""></a>
                                </td>
                                <td class="text-left"> {{c_item.product.name}}
                                    <br>
                                    SKU: {{c_item.product.id}}
                                    <br>
                                    Unit Price: ${{c_item.product.price}}
                                    <br>
                                    Qty : {{c_item.quantity}} X ${{c_item.product.price}}
                                </td>
                                <td>
                                    ${{c_item.sub_total}}
                                </td>
                                {% if c_item.quantity < c_item.product.stock %}
                                    <td> 
                                        <a href="{% url 'cart:add_cart' c_item.product.id %}" class="custom_a"><i class="fas fa-cart-plus custom_icon"></i> </a> &nbsp;<a href="{% url 'cart:cart_remove' c_item.product.id %}"><i class="fas fa-minus-circle custom_icon"></i></a> &nbsp;<a href=""><i class="fas fa-trash custom_icon"></i></a>
                                    </td>
                                {% else %}
                                <td> 
                                 &nbsp;<a href="{% url 'cart:cart_remove' c_item.product.id %}"><i class="fas fa-minus-circle custom_icon"></i></a> &nbsp;<a href=""><i class="fas fa-trash custom_icon"></i></a>
                                </td>
                                <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>


            </div>
           <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
               <table class="table my_custom_table">
                   <thead class="my_custom_thead">
                       <tr>
                           <th>
                               Checout
                           </th>
                       </tr>
                   </thead>
                   <tbody>
                       <tr> 
                           <td>
                               Please review the order - then proceed to checkout 
                           </td>
                       </tr>
                       <tr>
                           <td class="text-left">
                                Your Total is : <strong>{{ total }}</strong>
                           </td>
                       </tr>
                   </tbody>
               </table>
               <div class="mx-auto">
                   <a href="{% url 'shop:allProdCat'%}" class="btn btn-secondary btn-block my_custom_btn"> Continue shopping  </a>
               </div>
           </div>
        </div>
        <br>
        {% endif %}
{% endblock %}

search_app/templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
   This is the place holder  for MetaDesc : in Search_app 
{%  endblock %}
{% block title %}
   Search Result
{% endblock %}

{% block content %}
    <div>
        <p class="text-center my_search_text"> Search result for <b>" {{ query }}"</b> </p>
    </div>
    <div class="container">
        <div class="row mx-auto">
            {% for product in products %}
            <div class="my_button_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{ product.get_url }}"><img  class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name}}"></a>
                    <div class="card-body">
                        <h4> {{ product.name }} </h4>
                        <p class="card-text">$ {{ product.price }}</p>
                    </div>
                </div>
                {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text"> NO Results</p>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/base.html
{% load staticfiles %}
<! DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="{% block metadescription %} {% endblock %}">
        <link href="https://fonts.googleapis.com/css2?family=Bellota+Text&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">

        <title>{%  block title %}{% endblock %}</title>
    </head>

    <body>
        
            <div class="container">
                    {% include 'header.html' %}
                    {% include 'navbar.html' %}
                    {% block content %}
                    {% endblock %}
            </div>
            {% include 'footer.html' %}
            <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
            <script src="{% static 'js/popper.min.js' %}"></script>
            <script src="{% static '/js/bootstrap.min.js' %}"></script>

    </body>
</html>

shop/templates/footer.html
<div class="footer nav-bar-button my_footer">
    <p> CloudCart All right reserved</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"></a><img src="{% static 'img/logo.png' %}" alt="Cloud Cart Store">
    </center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Shop
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
              {% for cat in links %}
              <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}} </a>
              {% endfor %}
            </div>
          </li>
        {% if item_count > 0  %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{ item_count }})</a>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" get="">
        {% csrf_token%}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </nav>

shop/templates/shop/category.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Wlecome to Cushon store
    {% endif %}
{%  endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -Perfect CUshon store
    {% else %}
        See our cushon collection
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">Our Products </a> | {{category.name}}</p>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{  category.name }}</h1>
        <p class="text-justify">  {{ category.description }}</p>
    </div>
    {% else %}
        <img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" alt="Our product collection">

        <br>
        <div>
            <h1 class="text-center my_title">Our Product collection </h1>
            <p class="text-justify">Findng the perfect cushon and putting up in your room shoiuld be awesome </p>
        </div>
    {% endif %}
    <div class="container">
        <div class="row mx-auto">
            {% for product in products %}
            <div class="my_button_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{ product.get_url }}"><img  class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name}}"></a>
                    <div class="card-body">
                        <h4> {{ product.name }} </h4>
                        <p class="card-text">$ {{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %}active{% endif %}">{{ pg }}</a>
                {% endfor%}
            </div>
            {% endif %}

        </div>
        <br>
    </div>
    {% endblock %}

shop/templates/shop/product.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{%  endblock %}

{% block title %}
    {{ product.name }} -Perfect CUshon store
{% endblock %}

{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">Home | <a href="{{ product.category.get_url }}"> {{ product.category }} </a> | {{ product.name }} </a></p>
        </div>
        <div class="container">
            <br>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div style="min-width: 18rem;">
                        <img src="{{ product.image.url }}" alt="product.name">
                    </div>
                </div>
                <div>
                    <div>
                        <h1 class="my_prod_title">{{ product.name }}</h1>
                        <p>{{ product.price }}</p>
                        <p class="my_title"> Product Descriotion: </p>
                        <p class="text-justify my_prod_text"> {{ product.description }}</p>
                        {% if product.stock <= 0 %}
                            <p class="text-justify my_prod_text"> <b>Out of stock </b></p>
                        {% else %}
                            <a class="btn btn-outline-primary" href="{% url 'cart:add_cart' product.id %}">Add to Cart </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}